export type GPSCollector = {
  time: string,
  lat: number,
  lon: number,
  raw: string,
  type: string,
  valid: boolean,
  status?: string,
  faa?: string,
  alt?: number,
  quality?: string,
  satellites?: number,
  hdop?: number,
  geoidal?: number,
  age?: number,
  stationID?: any,
  speed?: number,
  track?: any,
  variation?: any,
  navStatus?: any,
}
